image:
  repository: registry.pheonix.live/phoenix-booking/frontend
  tag: "v1.0.0"

replicaCount: 2

serviceAccount:
  name: frontend-sa # The identity used to fetch OIDC configuration

service:
  port: 8080 # Port Nginx is exposed on in the container

imagePullSecret:
  # Provide a default name here. It will be overridden, but prevents the crash.
  name: "harbor-pull-secret"

resources:
  requests:
    cpu: "50m"
    memory: "128Mi"