apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: vault-vs
  namespace: vault
spec:
  hosts:
  - vault.pheonix.live
  gateways:
  # Syntax: <namespace>/<gateway-name>
  - istio-ingress/main-gateway
  http:
  # 1. Redirect HTTP to HTTPS (Smart Redirect)
  - match:
    - uri:
        prefix: /
      port: 80
    redirect:
      scheme: https
      port: 443
  
  # 2. Route HTTPS traffic to Vault
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: platform-vault-ui.vault.svc.cluster.local
        port:
          number: 8200
