apiVersion: v1
kind: Service
metadata:
  name: reservation-service
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    protocol: TCP
    name: http-app # Istio will use this name for protocol detection
  - port: 15020
    targetPort: 15020
    protocol: TCP
    name: istio-metrics # Istio proxy metrics port
  selector:
    app: reservation-service
  type: ClusterIP
