# Defines default variables used in the template files

image:
  repository: registry.phoenix-project.online/phoenix-staging/notification-service # Uses your new registry
  tag: "v1.0.0"


imagePullSecret:
  # Provide a default name here. It will be overridden, but prevents the crash.
  name: "harbor-pull-secret"

serviceAccount:
  name: notification-sa # CRITICAL: Service Account for Vault Auth

service:
  port: 3005 # Internal application port (health check only)

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "300m"
    memory: "512Mi"
