apiVersion: v1
kind: Service
metadata:
  name: hotel-service
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    protocol: TCP
    name: http-app # Istio will use this name for protocol detection
  selector:
    app: hotel-service
  type: ClusterIP
