# Defines default variables used in the template files

image:
  repository: registry.pheonix.live/phoenix-staging/reservation-service # Uses your new registry
  tag: "v1.0.0"


rabbitmq:
  # This must match the name of the broker's internal Secret
  secretName: "rabbitmq" 
  # This must match the key for the password in that Secret
  passwordKey: "rabbitmq-password"
  # This is the user that exists in the broker's database
  username: "user"

imagePullSecret:
  # Provide a default name here. It will be overridden, but prevents the crash.
  name: "harbor-pull-secret"

serviceAccount:
  name: reservation-sa # CRITICAL: Service Account for Vault Auth

service:
  port: 3004 # Internal application port

serviceEndpoints:
  hotel: "http://hotel-service:3002"
  room: "http://room-service:3003"

notification:
  fromEmail: "noreply@phoenix-booking.com"

rabbitmq:
  # CRITICAL: Define the correct service name explicitly
  serviceHost: phoenix-staging-rabbitmq-rabbitmq-broker

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "300m"
    memory: "512Mi"
